### ISSUE TITLE
[InvalidArgumentException]

### ISSUE THREAD

**Issue by mak147** [mageplaza/magento-2-urdu-language-pack#2]
composer require mageplaza/magento-2-urdu-language-pack:dev-master

Could not find a matching version of package mageplaza/magento-2-urdu-language-pack. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

I get this error on magento 2.2.2 please help

**Comment by legendhorus** [comment]
We have fixed the issue. You can re-install it now.

**Comment by mak147** [comment]
Thankyou so much for replaying
